import React from "react";
import {
  Boxes,
  Cloud,
  CloudCog,
  Code2,
  Container,
  Database,
  GitBranch,
  LockKeyhole,
  Network,
  Server,
  ShieldCheck,
  TerminalSquare,
  Workflow,
  Zap,
} from "lucide-react";

const TOPIC_ICON_MAP = {
  "Cloud Infrastructure": CloudCog,
  Docker: Container,
  Kubernetes: Boxes,
  "CI/CD": Workflow,
  Linux: TerminalSquare,
  Networking: Network,
  "Infrastructure as Code": Boxes,
  Security: ShieldCheck,
  Nginx: Server,
  "Git / GitHub": GitBranch,
  Python: Code2,
  "Java / Spring Boot": Code2,
  "Full Stack Web Development": Code2,
  "CompTIA Security+": ShieldCheck,
  "Certified Ethical Hacker (CEH)": ShieldCheck,
  CISSP: LockKeyhole,
  "CEH v13 + AI": ShieldCheck,
  "Django Notes App": Code2,
  "Two-Tier Flask App": Code2,
  "Expense Tracker WebApp": Database,
  "Cinematic React Portfolio": Code2,
  "Kubernetes Lab": Boxes,
  "Cybersecurity Learning Labs": ShieldCheck,
  Django: Code2,
  Flask: Code2,
  Java: Code2,
  "Spring Boot": Code2,
  JavaScript: Code2,
  "Framer Motion": Workflow,
  CSS: Code2,
  MySQL: Database,
  "Docker Compose": Container,
  "Docker Network": Network,
  Containers: Container,
  kubectl: Boxes,
  Wireshark: Network,
  Metasploit: ShieldCheck,
  "Security Labs": ShieldCheck,
  Git: GitBranch,
  Terraform: Boxes,
  React: Code2,
  Vite: Code2,
  AWS: CloudCog,
};

export function TopicIcon({ topic, size = 18 }) {
  const Icon = TOPIC_ICON_MAP[topic] || Zap;
  return <Icon size={size} aria-hidden="true" />;
}
